"""Integration test for MCP server with JWT authentication - Hello World example."""

import json
import os
import subprocess
import pytest
import pytest_asyncio
from asgi_lifespan import LifespanManager
from httpx import AsyncClient, ASGITransport
from src.p8fs_api.main import app


@pytest_asyncio.fixture
async def client():
    """Create async test client with proper lifespan management."""
    async with LifespanManager(app) as manager:
        async with AsyncClient(
            transport=ASGITransport(app=manager.app), 
            base_url="http://testserver"
        ) as client:
            yield client


@pytest.fixture
def jwt_token():
    """Get JWT token from saved file or generate it."""
    token_file = os.path.expanduser("~/.p8fs/auth/token.json")
    
    # Check if token file exists, if not generate it
    if not os.path.exists(token_file):
        # Run get_dev_jwt.py to generate token
        script_path = os.path.join(os.path.dirname(__file__), "../../scripts/dev/get_dev_jwt.py")
        result = subprocess.run(
            ["python", script_path, "--email", "test@example.com"],
            capture_output=True,
            text=True
        )
        if result.returncode != 0:
            pytest.skip(f"Failed to generate JWT token: {result.stderr}")
    
    # Read token from file
    try:
        with open(token_file) as f:
            token_data = json.load(f)
            return token_data["access_token"]
    except Exception as e:
        pytest.skip(f"Failed to read JWT token: {e}")


class TestMCPAuthIntegration:
    """Integration tests for MCP server with JWT authentication."""
    
    async def test_mcp_hello_world_with_dev_jwt_auth(self, client, jwt_token):
        """Test MCP about tool with dev JWT authentication - our Hello World example.
        
        NOTE: This test uses a JWT token generated by scripts/dev/get_dev_jwt.py
        and saved to ~/.p8fs/auth/token.json
        """
        
        # Step 1: Initialize MCP session
        init_request = {
            "jsonrpc": "2.0",
            "id": 1,
            "method": "initialize",
            "params": {
                "protocolVersion": "2024-11-05",
                "capabilities": {},
                "clientInfo": {
                    "name": "p8fs-test-client",
                    "version": "1.0.0"
                }
            }
        }
        
        init_response = await client.post(
            "/api/mcp",
            json=init_request,
            headers={
                "Authorization": f"Bearer {jwt_token}",
                "Accept": "application/json, text/event-stream"
            }
        )
        
        if init_response.status_code != 200:
            print(f"Init response status: {init_response.status_code}")
            print(f"Init response body: {init_response.text}")
        assert init_response.status_code == 200
        
        # Extract session ID from initialize response
        # FastMCP returns session ID in lowercase header
        session_id = init_response.headers.get("mcp-session-id")
        assert session_id, "No session ID returned from initialize"
        
        # Parse the initialize response to ensure it completed
        if init_response.text.startswith("event:"):
            import json
            lines = init_response.text.strip().split('\r\n')
            for line in lines:
                if line.startswith("data: "):
                    data_str = line[6:]
                    init_data = json.loads(data_str)
                    # Verify initialization succeeded
                    assert "result" in init_data, f"Initialize failed: {init_data}"
                    break
        
        # Step 2: Call MCP about tool with JWT authentication
        mcp_request = {
            "jsonrpc": "2.0",
            "id": 2,
            "method": "tools/call",
            "params": {
                "name": "about",
                "arguments": {}
            }
        }
        
        # Include session ID in headers
        headers = {
            "Authorization": f"Bearer {jwt_token}",
            "Accept": "application/json, text/event-stream",
            "mcp-session-id": session_id
        }
        
        response = await client.post(
            "/api/mcp",
            json=mcp_request,
            headers=headers
        )
        
        # Step 3: Verify successful response
        if response.status_code != 200:
            print(f"Response status: {response.status_code}")
            print(f"Response body: {response.text}")
        assert response.status_code == 200
        
        # Parse SSE response
        result_data = None
        if response.text.startswith("event:"):
            import json
            lines = response.text.strip().split('\r\n')
            for line in lines:
                if line.startswith("data: "):
                    data_str = line[6:]
                    result_data = json.loads(data_str)
                    break
        
        assert result_data is not None, "No data in response"
        
        # Check for error
        if "error" in result_data:
            print(f"MCP Error: {result_data['error']}")
            assert False, f"MCP returned error: {result_data['error']}"
        
        assert "result" in result_data
        assert "content" in result_data["result"]
        
        # Verify the about content
        content = result_data["result"]["content"][0]["text"]
        assert "P8FS" in content
        assert "distributed content management system" in content
        assert "secure" in content
        assert "SeaweedFS" in content
        assert "TiDB/TiKV" in content
        
        print("\n✅ MCP Hello World Success!")
        print(f"Response: {content[:100]}...")
    
    async def test_mcp_requires_authentication(self, client):
        """Test that MCP server requires authentication."""
        # Try to call about tool without authentication
        mcp_request = {
            "jsonrpc": "2.0",
            "id": 1,
            "method": "tools/call",
            "params": {
                "name": "about",
                "arguments": {}
            }
        }
        
        response = await client.post("/api/mcp", json=mcp_request)
        
        # Should return 401 Unauthorized
        assert response.status_code == 401
        
        error_data = response.json()
        assert error_data["error"] == "authentication_required"
        assert "JWT token required" in error_data["error_description"]
        assert "oauth_discovery" in error_data
        assert "instructions" in error_data
    
    async def test_mcp_with_invalid_token(self, client):
        """Test MCP server with invalid JWT token."""
        mcp_request = {
            "jsonrpc": "2.0",
            "id": 1,
            "method": "tools/call",
            "params": {
                "name": "about",
                "arguments": {}
            }
        }
        
        response = await client.post(
            "/api/mcp",
            json=mcp_request,
            headers={"Authorization": "Bearer invalid-token"}
        )
        
        # Should return 401 Unauthorized
        assert response.status_code == 401
    
    async def test_mcp_user_info_tool_with_auth(self, client, jwt_token):
        """Test MCP user_info tool returns authenticated user details."""
        
        # Call user_info tool
        mcp_request = {
            "jsonrpc": "2.0",
            "id": 2,
            "method": "tools/call",
            "params": {
                "name": "user_info",
                "arguments": {}
            }
        }
        
        response = await client.post(
            "/api/mcp",
            json=mcp_request,
            headers={
                "Authorization": f"Bearer {jwt_token}",
                "Accept": "application/json, text/event-stream"
            }
        )
        
        assert response.status_code == 200
        
        data = response.json()
        result = data["result"]["content"][0]["text"]
        
        # Parse the user info from the tool response
        import json
        user_info = json.loads(result)
        
        assert user_info["authenticated"] is True
        assert "email" in user_info
        assert "tenant_id" in user_info
        assert "user_id" in user_info
    
    async def test_mcp_oauth_discovery_endpoint(self, client):
        """Test MCP OAuth discovery endpoint."""
        response = await client.get("/api/mcp/auth/discovery")
        
        assert response.status_code == 200
        
        discovery = response.json()
        assert "device_authorization_endpoint" in discovery
        assert "token_endpoint" in discovery
        assert "authorization_endpoint" in discovery
        assert "issuer" in discovery
        
        # Verify endpoints are correctly formatted
        assert "/api/v1/oauth/device_authorization" in discovery["device_authorization_endpoint"]
        assert "/api/v1/oauth/token" in discovery["token_endpoint"]
        assert "/api/v1/oauth/authorize" in discovery["authorization_endpoint"]
    
    async def test_mcp_tools_list_with_auth(self, client, jwt_token):
        """Test listing available MCP tools with authentication."""
        
        # List tools
        mcp_request = {
            "jsonrpc": "2.0",
            "id": 3,
            "method": "tools/list"
        }
        
        response = await client.post(
            "/api/mcp",
            json=mcp_request,
            headers={
                "Authorization": f"Bearer {jwt_token}",
                "Accept": "application/json, text/event-stream"
            }
        )
        
        assert response.status_code == 200
        
        data = response.json()
        tools = data["result"]["tools"]
        
        # Verify we have our expected tools
        tool_names = {tool["name"] for tool in tools}
        assert "about" in tool_names
        assert "user_info" in tool_names
        assert "search_content" in tool_names
        assert "upload_content" in tool_names
        
        # Verify tool descriptions
        about_tool = next(t for t in tools if t["name"] == "about")
        assert "P8FS system" in about_tool["description"]


async def test_complete_mcp_auth_flow_example(client, jwt_token):
    """Complete example of MCP authentication flow - suitable for documentation."""
    print("\n🚀 MCP Authentication Flow Example\n")
    
    # Step 1: Use pre-generated JWT token
    print("1️⃣ Using JWT token from ~/.p8fs/auth/token.json...")
    print(f"   ✅ Got JWT token: {jwt_token[:20]}...")
    
    # Step 2: Initialize MCP session
    print("\n2️⃣ Initializing MCP session...")
    init_request = {
        "jsonrpc": "2.0",
        "id": 1,
        "method": "initialize",
        "params": {
            "protocolVersion": "2024-11-05",
            "capabilities": {},
            "clientInfo": {
                "name": "p8fs-test-client",
                "version": "1.0.0"
            }
        }
    }
    
    response = await client.post(
        "/api/mcp",
        json=init_request,
        headers={
                "Authorization": f"Bearer {jwt_token}",
                "Accept": "application/json, text/event-stream"
            }
    )
    assert response.status_code == 200
    print("   ✅ MCP session initialized")
    
    # Step 3: Call about tool
    print("\n3️⃣ Calling 'about' tool...")
    about_request = {
        "jsonrpc": "2.0",
        "id": 2,
        "method": "tools/call",
        "params": {
            "name": "about",
            "arguments": {}
        }
    }
    
    response = await client.post(
        "/api/mcp",
        json=about_request,
        headers={
                "Authorization": f"Bearer {jwt_token}",
                "Accept": "application/json, text/event-stream"
            }
    )
    assert response.status_code == 200
    
    about_content = response.json()["result"]["content"][0]["text"]
    print(f"   ✅ About P8FS: {about_content[:80]}...")
    
    # Step 4: Get user info
    print("\n4️⃣ Getting authenticated user info...")
    user_info_request = {
        "jsonrpc": "2.0",
        "id": 3,
        "method": "tools/call",
        "params": {
            "name": "user_info",
            "arguments": {}
        }
    }
    
    response = await client.post(
        "/api/mcp",
        json=user_info_request,
        headers={
                "Authorization": f"Bearer {jwt_token}",
                "Accept": "application/json, text/event-stream"
            }
    )
    assert response.status_code == 200
    
    user_info = response.json()["result"]["content"][0]["text"]
    print(f"   ✅ User info: {user_info}")
    
    print("\n✨ MCP Authentication Flow Complete!\n")


if __name__ == "__main__":
    # Run tests directly for development
    pytest.main([__file__, "-v", "-s"])