-- Load AGE Graph Functions for P8FS
-- This script properly initializes the AGE extension and loads all graph functions
-- 
-- Usage: 
--   psql -h localhost -p 5438 -U postgres -d app -f load_age_functions.sql
--   or from within psql: \i /full/path/to/load_age_functions.sql

-- Ensure AGE extension is created
CREATE EXTENSION IF NOT EXISTS age CASCADE;

-- Set proper search path for AGE operations
SET search_path = ag_catalog, "$user", public;

-- Create p8graph if it doesn't exist
DO $$ 
BEGIN
    -- Check if graph exists
    IF NOT EXISTS (
        SELECT 1 FROM ag_catalog.ag_graph WHERE name = 'p8graph'
    ) THEN
        PERFORM ag_catalog.create_graph('p8graph');
        RAISE NOTICE 'Created graph: p8graph';
    ELSE
        RAISE NOTICE 'Graph p8graph already exists';
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        RAISE NOTICE 'Error creating graph: %', SQLERRM;
        RAISE;
END $$;

-- Test basic AGE functionality
DO $$
DECLARE
    test_result RECORD;
BEGIN
    -- Test if we can execute a simple cypher query
    FOR test_result IN
        SELECT * FROM ag_catalog.cypher('p8graph', $$
            MATCH (n)
            RETURN count(n) as node_count
            LIMIT 1
        $$) AS (node_count agtype)
    LOOP
        RAISE NOTICE 'AGE test successful. Current node count: %', test_result.node_count;
    END LOOP;
EXCEPTION
    WHEN OTHERS THEN
        RAISE NOTICE 'AGE functionality test failed: %', SQLERRM;
        RAISE;
END $$;

-- Now load the compiled functions file
-- This file is generated by compile_migrations.py from individual function files
\echo 'Loading P8FS graph functions...'
\echo 'Note: Run compile_migrations.py first to generate 03_functions.sql from individual function files'
\echo ''

-- The path below assumes you're in the p8fs directory
-- Adjust the path as needed for your environment
\i ../03_functions.sql

\echo ''
\echo 'AGE graph functions loaded successfully!'
\echo ''
\echo 'Test with:'
\echo "  SELECT * FROM p8.cypher_query('MATCH (n) RETURN count(n)');"