# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from . import filer_pb2 as filer__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in filer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SeaweedFilerStub:
    """////////////////////////////////////////////////

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LookupDirectoryEntry = channel.unary_unary(
                '/filer_pb.SeaweedFiler/LookupDirectoryEntry',
                request_serializer=filer__pb2.LookupDirectoryEntryRequest.SerializeToString,
                response_deserializer=filer__pb2.LookupDirectoryEntryResponse.FromString,
                _registered_method=True)
        self.ListEntries = channel.unary_stream(
                '/filer_pb.SeaweedFiler/ListEntries',
                request_serializer=filer__pb2.ListEntriesRequest.SerializeToString,
                response_deserializer=filer__pb2.ListEntriesResponse.FromString,
                _registered_method=True)
        self.CreateEntry = channel.unary_unary(
                '/filer_pb.SeaweedFiler/CreateEntry',
                request_serializer=filer__pb2.CreateEntryRequest.SerializeToString,
                response_deserializer=filer__pb2.CreateEntryResponse.FromString,
                _registered_method=True)
        self.UpdateEntry = channel.unary_unary(
                '/filer_pb.SeaweedFiler/UpdateEntry',
                request_serializer=filer__pb2.UpdateEntryRequest.SerializeToString,
                response_deserializer=filer__pb2.UpdateEntryResponse.FromString,
                _registered_method=True)
        self.AppendToEntry = channel.unary_unary(
                '/filer_pb.SeaweedFiler/AppendToEntry',
                request_serializer=filer__pb2.AppendToEntryRequest.SerializeToString,
                response_deserializer=filer__pb2.AppendToEntryResponse.FromString,
                _registered_method=True)
        self.DeleteEntry = channel.unary_unary(
                '/filer_pb.SeaweedFiler/DeleteEntry',
                request_serializer=filer__pb2.DeleteEntryRequest.SerializeToString,
                response_deserializer=filer__pb2.DeleteEntryResponse.FromString,
                _registered_method=True)
        self.AtomicRenameEntry = channel.unary_unary(
                '/filer_pb.SeaweedFiler/AtomicRenameEntry',
                request_serializer=filer__pb2.AtomicRenameEntryRequest.SerializeToString,
                response_deserializer=filer__pb2.AtomicRenameEntryResponse.FromString,
                _registered_method=True)
        self.StreamRenameEntry = channel.unary_stream(
                '/filer_pb.SeaweedFiler/StreamRenameEntry',
                request_serializer=filer__pb2.StreamRenameEntryRequest.SerializeToString,
                response_deserializer=filer__pb2.StreamRenameEntryResponse.FromString,
                _registered_method=True)
        self.AssignVolume = channel.unary_unary(
                '/filer_pb.SeaweedFiler/AssignVolume',
                request_serializer=filer__pb2.AssignVolumeRequest.SerializeToString,
                response_deserializer=filer__pb2.AssignVolumeResponse.FromString,
                _registered_method=True)
        self.LookupVolume = channel.unary_unary(
                '/filer_pb.SeaweedFiler/LookupVolume',
                request_serializer=filer__pb2.LookupVolumeRequest.SerializeToString,
                response_deserializer=filer__pb2.LookupVolumeResponse.FromString,
                _registered_method=True)
        self.CollectionList = channel.unary_unary(
                '/filer_pb.SeaweedFiler/CollectionList',
                request_serializer=filer__pb2.CollectionListRequest.SerializeToString,
                response_deserializer=filer__pb2.CollectionListResponse.FromString,
                _registered_method=True)
        self.DeleteCollection = channel.unary_unary(
                '/filer_pb.SeaweedFiler/DeleteCollection',
                request_serializer=filer__pb2.DeleteCollectionRequest.SerializeToString,
                response_deserializer=filer__pb2.DeleteCollectionResponse.FromString,
                _registered_method=True)
        self.Statistics = channel.unary_unary(
                '/filer_pb.SeaweedFiler/Statistics',
                request_serializer=filer__pb2.StatisticsRequest.SerializeToString,
                response_deserializer=filer__pb2.StatisticsResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/filer_pb.SeaweedFiler/Ping',
                request_serializer=filer__pb2.PingRequest.SerializeToString,
                response_deserializer=filer__pb2.PingResponse.FromString,
                _registered_method=True)
        self.GetFilerConfiguration = channel.unary_unary(
                '/filer_pb.SeaweedFiler/GetFilerConfiguration',
                request_serializer=filer__pb2.GetFilerConfigurationRequest.SerializeToString,
                response_deserializer=filer__pb2.GetFilerConfigurationResponse.FromString,
                _registered_method=True)
        self.TraverseBfsMetadata = channel.unary_stream(
                '/filer_pb.SeaweedFiler/TraverseBfsMetadata',
                request_serializer=filer__pb2.TraverseBfsMetadataRequest.SerializeToString,
                response_deserializer=filer__pb2.TraverseBfsMetadataResponse.FromString,
                _registered_method=True)
        self.SubscribeMetadata = channel.unary_stream(
                '/filer_pb.SeaweedFiler/SubscribeMetadata',
                request_serializer=filer__pb2.SubscribeMetadataRequest.SerializeToString,
                response_deserializer=filer__pb2.SubscribeMetadataResponse.FromString,
                _registered_method=True)
        self.SubscribeLocalMetadata = channel.unary_stream(
                '/filer_pb.SeaweedFiler/SubscribeLocalMetadata',
                request_serializer=filer__pb2.SubscribeMetadataRequest.SerializeToString,
                response_deserializer=filer__pb2.SubscribeMetadataResponse.FromString,
                _registered_method=True)
        self.KvGet = channel.unary_unary(
                '/filer_pb.SeaweedFiler/KvGet',
                request_serializer=filer__pb2.KvGetRequest.SerializeToString,
                response_deserializer=filer__pb2.KvGetResponse.FromString,
                _registered_method=True)
        self.KvPut = channel.unary_unary(
                '/filer_pb.SeaweedFiler/KvPut',
                request_serializer=filer__pb2.KvPutRequest.SerializeToString,
                response_deserializer=filer__pb2.KvPutResponse.FromString,
                _registered_method=True)
        self.CacheRemoteObjectToLocalCluster = channel.unary_unary(
                '/filer_pb.SeaweedFiler/CacheRemoteObjectToLocalCluster',
                request_serializer=filer__pb2.CacheRemoteObjectToLocalClusterRequest.SerializeToString,
                response_deserializer=filer__pb2.CacheRemoteObjectToLocalClusterResponse.FromString,
                _registered_method=True)
        self.DistributedLock = channel.unary_unary(
                '/filer_pb.SeaweedFiler/DistributedLock',
                request_serializer=filer__pb2.LockRequest.SerializeToString,
                response_deserializer=filer__pb2.LockResponse.FromString,
                _registered_method=True)
        self.DistributedUnlock = channel.unary_unary(
                '/filer_pb.SeaweedFiler/DistributedUnlock',
                request_serializer=filer__pb2.UnlockRequest.SerializeToString,
                response_deserializer=filer__pb2.UnlockResponse.FromString,
                _registered_method=True)
        self.FindLockOwner = channel.unary_unary(
                '/filer_pb.SeaweedFiler/FindLockOwner',
                request_serializer=filer__pb2.FindLockOwnerRequest.SerializeToString,
                response_deserializer=filer__pb2.FindLockOwnerResponse.FromString,
                _registered_method=True)
        self.TransferLocks = channel.unary_unary(
                '/filer_pb.SeaweedFiler/TransferLocks',
                request_serializer=filer__pb2.TransferLocksRequest.SerializeToString,
                response_deserializer=filer__pb2.TransferLocksResponse.FromString,
                _registered_method=True)


class SeaweedFilerServicer:
    """////////////////////////////////////////////////

    """

    def LookupDirectoryEntry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEntries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateEntry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEntry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendToEntry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEntry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AtomicRenameEntry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamRenameEntry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignVolume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LookupVolume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CollectionList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Statistics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFilerConfiguration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TraverseBfsMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeLocalMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KvGet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KvPut(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CacheRemoteObjectToLocalCluster(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DistributedLock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DistributedUnlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindLockOwner(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransferLocks(self, request, context):
        """distributed lock management internal use only
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SeaweedFilerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LookupDirectoryEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.LookupDirectoryEntry,
                    request_deserializer=filer__pb2.LookupDirectoryEntryRequest.FromString,
                    response_serializer=filer__pb2.LookupDirectoryEntryResponse.SerializeToString,
            ),
            'ListEntries': grpc.unary_stream_rpc_method_handler(
                    servicer.ListEntries,
                    request_deserializer=filer__pb2.ListEntriesRequest.FromString,
                    response_serializer=filer__pb2.ListEntriesResponse.SerializeToString,
            ),
            'CreateEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEntry,
                    request_deserializer=filer__pb2.CreateEntryRequest.FromString,
                    response_serializer=filer__pb2.CreateEntryResponse.SerializeToString,
            ),
            'UpdateEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEntry,
                    request_deserializer=filer__pb2.UpdateEntryRequest.FromString,
                    response_serializer=filer__pb2.UpdateEntryResponse.SerializeToString,
            ),
            'AppendToEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendToEntry,
                    request_deserializer=filer__pb2.AppendToEntryRequest.FromString,
                    response_serializer=filer__pb2.AppendToEntryResponse.SerializeToString,
            ),
            'DeleteEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEntry,
                    request_deserializer=filer__pb2.DeleteEntryRequest.FromString,
                    response_serializer=filer__pb2.DeleteEntryResponse.SerializeToString,
            ),
            'AtomicRenameEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.AtomicRenameEntry,
                    request_deserializer=filer__pb2.AtomicRenameEntryRequest.FromString,
                    response_serializer=filer__pb2.AtomicRenameEntryResponse.SerializeToString,
            ),
            'StreamRenameEntry': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamRenameEntry,
                    request_deserializer=filer__pb2.StreamRenameEntryRequest.FromString,
                    response_serializer=filer__pb2.StreamRenameEntryResponse.SerializeToString,
            ),
            'AssignVolume': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignVolume,
                    request_deserializer=filer__pb2.AssignVolumeRequest.FromString,
                    response_serializer=filer__pb2.AssignVolumeResponse.SerializeToString,
            ),
            'LookupVolume': grpc.unary_unary_rpc_method_handler(
                    servicer.LookupVolume,
                    request_deserializer=filer__pb2.LookupVolumeRequest.FromString,
                    response_serializer=filer__pb2.LookupVolumeResponse.SerializeToString,
            ),
            'CollectionList': grpc.unary_unary_rpc_method_handler(
                    servicer.CollectionList,
                    request_deserializer=filer__pb2.CollectionListRequest.FromString,
                    response_serializer=filer__pb2.CollectionListResponse.SerializeToString,
            ),
            'DeleteCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCollection,
                    request_deserializer=filer__pb2.DeleteCollectionRequest.FromString,
                    response_serializer=filer__pb2.DeleteCollectionResponse.SerializeToString,
            ),
            'Statistics': grpc.unary_unary_rpc_method_handler(
                    servicer.Statistics,
                    request_deserializer=filer__pb2.StatisticsRequest.FromString,
                    response_serializer=filer__pb2.StatisticsResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=filer__pb2.PingRequest.FromString,
                    response_serializer=filer__pb2.PingResponse.SerializeToString,
            ),
            'GetFilerConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFilerConfiguration,
                    request_deserializer=filer__pb2.GetFilerConfigurationRequest.FromString,
                    response_serializer=filer__pb2.GetFilerConfigurationResponse.SerializeToString,
            ),
            'TraverseBfsMetadata': grpc.unary_stream_rpc_method_handler(
                    servicer.TraverseBfsMetadata,
                    request_deserializer=filer__pb2.TraverseBfsMetadataRequest.FromString,
                    response_serializer=filer__pb2.TraverseBfsMetadataResponse.SerializeToString,
            ),
            'SubscribeMetadata': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeMetadata,
                    request_deserializer=filer__pb2.SubscribeMetadataRequest.FromString,
                    response_serializer=filer__pb2.SubscribeMetadataResponse.SerializeToString,
            ),
            'SubscribeLocalMetadata': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeLocalMetadata,
                    request_deserializer=filer__pb2.SubscribeMetadataRequest.FromString,
                    response_serializer=filer__pb2.SubscribeMetadataResponse.SerializeToString,
            ),
            'KvGet': grpc.unary_unary_rpc_method_handler(
                    servicer.KvGet,
                    request_deserializer=filer__pb2.KvGetRequest.FromString,
                    response_serializer=filer__pb2.KvGetResponse.SerializeToString,
            ),
            'KvPut': grpc.unary_unary_rpc_method_handler(
                    servicer.KvPut,
                    request_deserializer=filer__pb2.KvPutRequest.FromString,
                    response_serializer=filer__pb2.KvPutResponse.SerializeToString,
            ),
            'CacheRemoteObjectToLocalCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.CacheRemoteObjectToLocalCluster,
                    request_deserializer=filer__pb2.CacheRemoteObjectToLocalClusterRequest.FromString,
                    response_serializer=filer__pb2.CacheRemoteObjectToLocalClusterResponse.SerializeToString,
            ),
            'DistributedLock': grpc.unary_unary_rpc_method_handler(
                    servicer.DistributedLock,
                    request_deserializer=filer__pb2.LockRequest.FromString,
                    response_serializer=filer__pb2.LockResponse.SerializeToString,
            ),
            'DistributedUnlock': grpc.unary_unary_rpc_method_handler(
                    servicer.DistributedUnlock,
                    request_deserializer=filer__pb2.UnlockRequest.FromString,
                    response_serializer=filer__pb2.UnlockResponse.SerializeToString,
            ),
            'FindLockOwner': grpc.unary_unary_rpc_method_handler(
                    servicer.FindLockOwner,
                    request_deserializer=filer__pb2.FindLockOwnerRequest.FromString,
                    response_serializer=filer__pb2.FindLockOwnerResponse.SerializeToString,
            ),
            'TransferLocks': grpc.unary_unary_rpc_method_handler(
                    servicer.TransferLocks,
                    request_deserializer=filer__pb2.TransferLocksRequest.FromString,
                    response_serializer=filer__pb2.TransferLocksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'filer_pb.SeaweedFiler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('filer_pb.SeaweedFiler', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SeaweedFiler:
    """////////////////////////////////////////////////

    """

    @staticmethod
    def LookupDirectoryEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filer_pb.SeaweedFiler/LookupDirectoryEntry',
            filer__pb2.LookupDirectoryEntryRequest.SerializeToString,
            filer__pb2.LookupDirectoryEntryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/filer_pb.SeaweedFiler/ListEntries',
            filer__pb2.ListEntriesRequest.SerializeToString,
            filer__pb2.ListEntriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filer_pb.SeaweedFiler/CreateEntry',
            filer__pb2.CreateEntryRequest.SerializeToString,
            filer__pb2.CreateEntryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filer_pb.SeaweedFiler/UpdateEntry',
            filer__pb2.UpdateEntryRequest.SerializeToString,
            filer__pb2.UpdateEntryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendToEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filer_pb.SeaweedFiler/AppendToEntry',
            filer__pb2.AppendToEntryRequest.SerializeToString,
            filer__pb2.AppendToEntryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filer_pb.SeaweedFiler/DeleteEntry',
            filer__pb2.DeleteEntryRequest.SerializeToString,
            filer__pb2.DeleteEntryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AtomicRenameEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filer_pb.SeaweedFiler/AtomicRenameEntry',
            filer__pb2.AtomicRenameEntryRequest.SerializeToString,
            filer__pb2.AtomicRenameEntryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamRenameEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/filer_pb.SeaweedFiler/StreamRenameEntry',
            filer__pb2.StreamRenameEntryRequest.SerializeToString,
            filer__pb2.StreamRenameEntryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignVolume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filer_pb.SeaweedFiler/AssignVolume',
            filer__pb2.AssignVolumeRequest.SerializeToString,
            filer__pb2.AssignVolumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LookupVolume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filer_pb.SeaweedFiler/LookupVolume',
            filer__pb2.LookupVolumeRequest.SerializeToString,
            filer__pb2.LookupVolumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CollectionList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filer_pb.SeaweedFiler/CollectionList',
            filer__pb2.CollectionListRequest.SerializeToString,
            filer__pb2.CollectionListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filer_pb.SeaweedFiler/DeleteCollection',
            filer__pb2.DeleteCollectionRequest.SerializeToString,
            filer__pb2.DeleteCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Statistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filer_pb.SeaweedFiler/Statistics',
            filer__pb2.StatisticsRequest.SerializeToString,
            filer__pb2.StatisticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filer_pb.SeaweedFiler/Ping',
            filer__pb2.PingRequest.SerializeToString,
            filer__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFilerConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filer_pb.SeaweedFiler/GetFilerConfiguration',
            filer__pb2.GetFilerConfigurationRequest.SerializeToString,
            filer__pb2.GetFilerConfigurationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TraverseBfsMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/filer_pb.SeaweedFiler/TraverseBfsMetadata',
            filer__pb2.TraverseBfsMetadataRequest.SerializeToString,
            filer__pb2.TraverseBfsMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/filer_pb.SeaweedFiler/SubscribeMetadata',
            filer__pb2.SubscribeMetadataRequest.SerializeToString,
            filer__pb2.SubscribeMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeLocalMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/filer_pb.SeaweedFiler/SubscribeLocalMetadata',
            filer__pb2.SubscribeMetadataRequest.SerializeToString,
            filer__pb2.SubscribeMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def KvGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filer_pb.SeaweedFiler/KvGet',
            filer__pb2.KvGetRequest.SerializeToString,
            filer__pb2.KvGetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def KvPut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filer_pb.SeaweedFiler/KvPut',
            filer__pb2.KvPutRequest.SerializeToString,
            filer__pb2.KvPutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CacheRemoteObjectToLocalCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filer_pb.SeaweedFiler/CacheRemoteObjectToLocalCluster',
            filer__pb2.CacheRemoteObjectToLocalClusterRequest.SerializeToString,
            filer__pb2.CacheRemoteObjectToLocalClusterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DistributedLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filer_pb.SeaweedFiler/DistributedLock',
            filer__pb2.LockRequest.SerializeToString,
            filer__pb2.LockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DistributedUnlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filer_pb.SeaweedFiler/DistributedUnlock',
            filer__pb2.UnlockRequest.SerializeToString,
            filer__pb2.UnlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindLockOwner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filer_pb.SeaweedFiler/FindLockOwner',
            filer__pb2.FindLockOwnerRequest.SerializeToString,
            filer__pb2.FindLockOwnerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransferLocks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filer_pb.SeaweedFiler/TransferLocks',
            filer__pb2.TransferLocksRequest.SerializeToString,
            filer__pb2.TransferLocksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
